"""Stage 3 — Generate. Opportunity -> validated parameters -> a thin module.

The central bet of the whole product is here: **the model fills a schema, it does
not write Manim.** Everything about how a scene looks belongs to a tested
template; the model contributes parameters, captions and timing. That shrinks the
failure surface from "any Python" to "does this JSON validate", which is why
first-pass gate rates are worth measuring per archetype.

The generated module is deliberately about eight lines long. Its whole job is to
name a template, hand it validated parameters, and expose a Manim ``Scene``
subclass for the CLI to render. A short generated module is not a stylistic
preference — every line the model does not write is a line that cannot
hallucinate.
"""

from __future__ import annotations

import json
import logging
import pprint
import textwrap
from dataclasses import dataclass, field
from typing import Any

from arcvisual.analyze.prompts import (
    CODEGEN_SYSTEM,
    CODEGEN_TASK,
    REPAIR_TASK,
    ParamsOut,
    build_prompt,
)
from arcvisual.config import settings
from arcvisual.providers.base import (
    Provider,
    ProviderError,
    Task,
    TextBlock,
    Usage,
)
from arcvisual.providers.registry import get_provider
from arcvisual.storyboard import (
    Archetype,
    Beat,
    GateReport,
    Scene,
    SceneSpec,
    SceneState,
    Storyboard,
    VisualOpportunity,
)
from arcvisual.templates import registry
from arcvisual.templates.base import MIN_BEAT_S

log = logging.getLogger(__name__)


@dataclass
class GenerateResult:
    scene: Scene
    source: str
    params_obj: Any
    cost_usd: float = 0.0
    #: False when the provider's pricing is unknown to us.
    cost_attributed: bool = True
    provider: str = "heuristic"
    notes: list[str] = field(default_factory=list)


# --------------------------------------------------------------------------- #
# The generated module
# --------------------------------------------------------------------------- #

_MODULE_TEMPLATE = '''\
"""Generated by ArcVisual. Do not edit -- regenerate from the storyboard.

archetype : {archetype}
claim     : {claim}
grounded  : {section_id}[{span_start}:{span_end}]
"""

from {template_module} import Params, build
from arcvisual.templates.base import make_scene

SCENE_ID = {scene_id!r}
ARCHETYPE = {archetype!r}
PARAMS = Params(**{params_json})

# module=__name__ is required: Manim only discovers Scene subclasses whose
# __module__ matches the module it loaded.
{class_name} = make_scene(
    SCENE_ID, ARCHETYPE, build, PARAMS, trace_path={trace_path!r}, module=__name__
)
'''


def scene_class_name(scene_id: str) -> str:
    """The class name Manim's CLI is pointed at."""
    safe = "".join(c if c.isalnum() else "_" for c in scene_id)
    return f"ArcScene_{safe}"


def render_module(
    spec: SceneSpec, params_obj: Any, *, trace_path: str = "trace.json"
) -> str:
    """Emit the module for one scene. Deterministic: same spec, same bytes."""
    template = registry.get(spec.archetype)
    return _MODULE_TEMPLATE.format(
        archetype=spec.archetype.value,
        claim=spec.claim.replace("\n", " ")[:200],
        section_id=spec.span.section_id,
        span_start=spec.span.start,
        span_end=spec.span.end,
        template_module=template.import_path,
        scene_id=spec.id,
        # pprint, not json.dumps: JSON writes `false`/`true`/`null`, which are not
        # Python literals and would land in the module as undefined names. Gate 1
        # catches that, but burning an attempt on our own serialiser is waste.
        # sort_dicts keeps the bytes stable, which keeps the L2 cache warm.
        params_json=pprint.pformat(
            params_obj.model_dump(mode="json"), indent=4, width=84, sort_dicts=True
        ),
        class_name=scene_class_name(spec.id),
        trace_path=trace_path,
    )


# --------------------------------------------------------------------------- #
# Parameter filling
# --------------------------------------------------------------------------- #


def generate_scene(
    sb: Storyboard,
    opportunity: VisualOpportunity,
    *,
    provider: Provider | None = None,
    client: object | None = None,
    previous: dict[str, Any] | None = None,
    findings: list[str] | None = None,
    attempt: int = 1,
) -> GenerateResult:
    """Fill one scene's parameters.

    Passing ``findings`` turns this into a repair call: the failing gate output
    goes back to the model with an instruction to change the least that resolves
    it. Repair is parameter adjustment, never a code rewrite — which is the whole
    reason templates are worth their cost.
    """
    section = sb.section(opportunity.span.section_id)
    source_text = opportunity.span.resolve(section)

    if provider is None and client is not None:
        from arcvisual.providers.anthropic_provider import AnthropicProvider

        provider = AnthropicProvider(client=client)
    if provider is None:
        provider = get_provider()

    # A custom scene has no template to fill: the model writes the Manim itself.
    # Dispatched here rather than inside the template registry because the two paths
    # differ in what the model produces, not in how the result is handled — the
    # GenerateResult that comes back goes through the same gates, the same repair
    # ladder and the same cache.
    if opportunity.archetype is Archetype.CUSTOM_SCENE:
        if provider is None:
            # Nothing to fall back on: there is no heuristic that writes an
            # animation. Say so plainly rather than emitting a stub that renders an
            # empty frame and reports success.
            scene = Scene(
                spec=_spec(opportunity, {}, [], False),
                state=SceneState.GENERATING,
                attempts=attempt,
                gate_report=GateReport(),
            )
            return GenerateResult(
                scene=scene,
                source="",
                params_obj=None,
                cost_usd=0.0,
                cost_attributed=True,
                provider="heuristic",
                notes=["custom_scene needs a model provider; none is configured"],
            )
        from arcvisual.generate.custom_codegen import generate_custom

        return generate_custom(
            sb,
            opportunity,
            provider=provider,
            findings=findings,
            attempt=attempt,
        )

    template = registry.get(opportunity.archetype)

    if provider is None:
        raw_params, beats, scrubbable = heuristic_params(sb, opportunity)
        usage = Usage(attributed=True)  # genuinely free: no call was made
        notes = ["heuristic parameters — no model provider configured"]
    else:
        raw_params, beats, scrubbable, usage = _call_provider(
            sb,
            opportunity,
            source_text,
            provider=provider,
            previous=previous,
            findings=findings,
            attempt=attempt,
        )
        notes = []
    cost = usage.cost_usd

    # Validate before building the spec: an invalid parameter set must not reach
    # a SceneSpec, because the spec is what gets content-hashed.
    params_obj, param_findings = registry.validate_or_error(
        opportunity.archetype, raw_params
    )
    if params_obj is None:
        scene = Scene(
            spec=_spec(opportunity, raw_params, beats, scrubbable),
            state=SceneState.GENERATING,
            attempts=attempt,
            gate_report=GateReport(),
        )
        return GenerateResult(
            scene=scene,
            source="",
            params_obj=None,
            cost_usd=cost,
            cost_attributed=usage.attributed,
            provider=provider.name if provider else "heuristic",
            notes=[*notes, *param_findings],
        )

    # Captions live on the beats and are mirrored into params so a template body
    # never needs the storyboard.
    if hasattr(params_obj, "captions") and not params_obj.captions:
        params_obj = params_obj.model_copy(
            update={"captions": [b.caption for b in beats][: _caption_cap(params_obj)]}
        )

    # Reconcile the beat timeline with what the template will actually play. The
    # template owns timing (the plan's own split of responsibilities), so the
    # model's durations are advisory and its caption COUNT is what matters. Without
    # this, Gate 2's +/-20% duration assertion fires on every scene and tells us
    # nothing about real drift.
    beats = fit_beats([b.caption for b in beats], template.estimate_duration(params_obj))
    spec = _spec(opportunity, params_obj.model_dump(mode="json"), beats, scrubbable)
    source = render_module(spec, params_obj)
    scene = Scene(spec=spec, state=SceneState.VALIDATING, attempts=attempt)
    return GenerateResult(
        scene=scene,
        source=source,
        params_obj=params_obj,
        cost_usd=cost,
        cost_attributed=usage.attributed,
        provider=provider.name if provider else "heuristic",
        notes=notes,
    )


def fit_beats(captions: list[str], total_s: float) -> list[Beat]:
    """Lay captions end to end across a runtime the template dictates.

    Distribution is even. Captions are burned into the video by the template, so
    beat times are metadata for the reader rather than a cue track — what has to be
    right is the total, which is what Gate 2 checks.

    If the runtime cannot seat every caption above the 0.8s pacing floor, captions
    are dropped rather than rushed: a caption nobody can read is worse than one
    fewer caption.
    """
    captions = [c for c in captions if c.strip()] or [""]
    seatable = max(1, int(total_s // MIN_BEAT_S))
    if len(captions) > seatable:
        captions = captions[:seatable]
    # Round the duration ONCE, then accumulate the rounded value. Accumulating the
    # raw quotient while storing a rounded `dur` makes the two disagree: a 6.2s
    # runtime over 3 captions gave dur=2.067 but t=4.133, so beat 1 ended at 4.134
    # and beat 2 began at 4.133 — a 1ms overlap that failed the SceneSpec validator
    # and cost the scene every attempt. Only shows up when the quotient does not
    # divide evenly, which is why round-numbered test fixtures never caught it.
    each = round(max(MIN_BEAT_S, total_s / len(captions)), 3)
    beats: list[Beat] = []
    t = 0.0
    for caption in captions:
        beats.append(Beat(t=round(t, 3), dur=each, caption=caption))
        t = round(t + each, 3)
    return beats


def _caption_cap(params_obj: Any) -> int:
    field = type(params_obj).model_fields.get("captions")
    if field is None:
        return 12
    for meta in field.metadata:
        if (cap := getattr(meta, "max_length", None)) is not None:
            return int(cap)
    return 12


def _spec(
    opportunity: VisualOpportunity,
    params: dict[str, Any],
    beats: list[Beat],
    scrubbable: bool,
) -> SceneSpec:
    return SceneSpec(
        id=opportunity.id,
        archetype=opportunity.archetype,
        claim=opportunity.claim,
        concept_id=opportunity.concept_id,
        span=opportunity.span,
        params=params,
        beats=tuple(beats),
        scrubbable=scrubbable,
        priority=round((5 - opportunity.difficulty) * 10 - opportunity.rank),
    )


def _call_provider(
    sb: Storyboard,
    opportunity: VisualOpportunity,
    source_text: str,
    *,
    provider: Provider,
    previous: dict[str, Any] | None,
    findings: list[str] | None,
    attempt: int,
) -> tuple[dict[str, Any], list[Beat], bool, Usage]:
    cfg = settings()
    template = registry.get(opportunity.archetype)
    concept = sb.concept(opportunity.concept_id)
    section = sb.section(opportunity.span.section_id)
    equations = [e.latex for e in sb.equations if e.span.section_id == section.id] or [
        "(none in this section)"
    ]

    # Reuse the analyze prefix verbatim so a caching provider reads the paper body
    # back instead of re-sending it. Order matters: the cached prefix must stay
    # byte-identical, so the codegen-specific blocks go strictly after it.
    #
    # The provider's budget has to be honoured HERE too, not only in Analyze. Without
    # it this rebuilt the full-paper prompt for every scene and every repair attempt:
    # ~20,431 tokens against an 8,000-token-per-minute ceiling, so codegen failed 413
    # on arrival and every scene degraded. Reusing the analyze prefix keeps it
    # byte-identical for a caching provider precisely because both callers pass the
    # same budget — the reuse is what makes them agree, not an exception to it.
    #
    # And it is only worth sending AT ALL to a provider that caches it. Codegen does
    # not read the paper: it is given the claim, the concept, this section's own
    # source text and its equations, which is everything the schema asks it to fill.
    # The body rides along purely so a caching provider can read the prefix back
    # instead of re-sending it. Without a cache that trade inverts — the body is
    # re-sent per scene AND per repair attempt, ~20,431 tokens each time against an
    # 8,000-per-minute ceiling, which is what made every scene fail 413 on arrival.
    caps = provider.capabilities()
    prefix: list[TextBlock] = []
    if caps.prompt_cache:
        prefix, _ = build_prompt(sb, caps.prompt_char_budget, caps.analysis_item_budget)
    system_blocks = [
        *prefix,
        TextBlock(text=CODEGEN_SYSTEM),
        TextBlock(
            text="The parameter schema you must fill:\n"
            + json.dumps(template.param_schema(), indent=2)
        ),
    ]

    user = CODEGEN_TASK.format(
        archetype=opportunity.archetype.value,
        claim=opportunity.claim,
        concept=f"{concept.name} — {concept.statement}",
        source=source_text[:1500],
        equations="\n".join(f"  {eq}" for eq in equations[:6]),
        max_runtime=int(cfg.render.max_runtime_s),
    )
    if findings:
        user += "\n\n" + REPAIR_TASK.format(
            archetype=opportunity.archetype.value,
            attempt=attempt - 1,
            findings="\n".join(f"  - {f}" for f in findings[:12]),
            previous=json.dumps(previous or {}, indent=2, sort_keys=True)[:2500],
        )

    result = provider.structured(
        system=system_blocks,
        user=user,
        output_model=ParamsOut,
        task=Task.CODEGEN,
        max_tokens=cfg.models.max_tokens,
    )
    parsed: ParamsOut | None = result.value
    if parsed is None:
        # A scene, not the job, fails here — repair.py records the findings as a
        # Gate 1 failure and spends the next attempt on them.
        raise ProviderError(
            f"codegen got no parsable output from {result.provider}: "
            + "; ".join(result.findings or ["unknown reason"])
        )

    return parsed.params, _beats_from(parsed), bool(parsed.scrubbable), result.usage


def _beats_from(parsed: ParamsOut) -> list[Beat]:
    """Lay the model's durations end to end. The model gives durations, not start
    times — asking for absolute ``t`` values invites arithmetic errors that the
    ``SceneSpec`` overlap validator would reject."""
    beats: list[Beat] = []
    t = 0.0
    for b in parsed.beats:
        beats.append(Beat(t=round(t, 3), dur=b.dur, caption=b.caption))
        t += b.dur
    return beats


# --------------------------------------------------------------------------- #
# Offline parameter filling
# --------------------------------------------------------------------------- #


def _chain_steps(equations: list[str]) -> list[str]:
    """Two or three genuinely different states for a transform chain.

    Repeating one equation would render a no-op transform, which Gate 3 sees as
    dead air and which teaches the reader nothing. With a single equation
    available, the honest chain is "the shape of the statement" then "the
    statement": show the left-hand side first, then let the right-hand side
    arrive. That is a real progressive disclosure rather than a padded one.
    """
    unique: list[str] = []
    for eq in equations:
        flat = " ".join(eq.split())
        if flat and flat not in unique:
            unique.append(flat)
    if len(unique) >= 2:
        return unique[:3]
    if len(unique) == 1 and "=" in unique[0]:
        lhs, _, _rhs = unique[0].partition("=")
        return [f"{lhs.strip()} = \\;?", unique[0]]
    if unique:
        return [unique[0], unique[0] + " \\quad \\checkmark"]
    return ["y = f(x)", "y = f(g(x))"]


def heuristic_params(
    sb: Storyboard, opportunity: VisualOpportunity
) -> tuple[dict[str, Any], list[Beat], bool]:
    """Deterministic parameters built from the paper itself, no model involved.

    Phase 1's build order calls for validating the templates with hand-filled
    parameters *before* trusting codegen. This is that path, mechanised so the
    eval harness can run end-to-end in CI without a key.
    """
    section = sb.section(opportunity.span.section_id)
    arch = opportunity.archetype.value

    if arch == "transform_chain":
        eqs = [e.latex for e in sb.equations if e.span.section_id == section.id]
        steps = _chain_steps(eqs)
        params = {
            "steps": steps,
            "title": section.heading[:80],
            "highlight": [],
        }
        captions = [f"Start from the paper's {section.heading.lower()}."] + [
            f"Step {i + 2}." for i in range(len(steps) - 1)
        ]

    elif arch == "plot_reveal":
        params = {
            "x_label": "training steps",
            "y_label": "score",
            "series": [
                {
                    "label": "reported",
                    "points": [[0, 10.0], [1, 18.0], [2, 23.5], [3, 26.0], [4, 28.4]],
                    "annotate_at": 4,
                }
            ],
            "takeaway": None,
        }
        captions = ["The reported trend, drawn as it forms.", "The final figure."]

    else:  # architecture_flow
        params = {
            "nodes": [
                {"id": "input", "label": "Input", "column": 0},
                {
                    "id": "core",
                    "label": section.heading[:36] or "Model",
                    "column": 1,
                    "emphasis": True,
                },
                {"id": "output", "label": "Output", "column": 2},
            ],
            "edges": [
                {"src": "input", "dst": "core"},
                {"src": "core", "dst": "output"},
            ],
            "trace_path": ["input", "core", "output"],
        }
        captions = [
            "Input enters the model.",
            "The paper's contribution sits here.",
            "And the output leaves.",
            "Follow one example through.",
        ]

    beats: list[Beat] = []
    t = 0.0
    for cap in captions:
        beats.append(Beat(t=round(t, 3), dur=2.0, caption=textwrap.shorten(cap, 90)))
        t += 2.0
    params["captions"] = captions
    return params, beats, False
